spring:
  application:
    name: clinic

server:
  port: 8080

jwt:
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
